# Pure black for OLED screens: saves battery, very dark.
"keyboardBackgroundColor":"ff000000"
"keyBorderColor":"ff1f1f1f"
"keyBackgroundColor":"ff121212"
"keyPressedBackgroundColor":"ff2a2a2a"
"primaryTextColor":"ffffffff"
"secondaryTextColor":"70ffffff"
"metaBackgroundColor":"ff004d40"
"metaPressedBackgroundColor":"ff00796b"
"shadowColor":"aa000000"
"keyPreviewBackgroundColor":"ff1e1e1e"
"previewTextColor":"ffffffff"
"previewSelectedColor":"8800bfa5"
