# Calm dark green.
"keyboardBackgroundColor":"ff1b2a1f"
"keyBorderColor":"ff121c15"
"keyBackgroundColor":"ff2b3d30"
"keyPressedBackgroundColor":"ff3b5242"
"primaryTextColor":"ffe3efe6"
"secondaryTextColor":"80c8dccd"
"metaBackgroundColor":"ff3e6b4a"
"metaPressedBackgroundColor":"ff2e7d32"
"shadowColor":"88000000"
"keyPreviewBackgroundColor":"ff2b3d30"
"previewTextColor":"ffe3efe6"
"previewSelectedColor":"8866bb6a"
