# Fresh light blue.
"keyboardBackgroundColor":"ffdcecf7"
"keyBorderColor":"331565c0"
"keyBackgroundColor":"ffffffff"
"keyPressedBackgroundColor":"ffc6dcef"
"primaryTextColor":"ff0d2b45"
"secondaryTextColor":"66103a5c"
"metaBackgroundColor":"ff90caf9"
"metaPressedBackgroundColor":"ff1e88e5"
"shadowColor":"55000000"
"keyPreviewBackgroundColor":"ffffffff"
"previewTextColor":"ff0d2b45"
"previewSelectedColor":"551e88e5"
