# Soft light pink.
"keyboardBackgroundColor":"fff8e1e7"
"keyBorderColor":"33880e4f"
"keyBackgroundColor":"ffffffff"
"keyPressedBackgroundColor":"fff3cbd6"
"primaryTextColor":"ff4a1830"
"secondaryTextColor":"66880e4f"
"metaBackgroundColor":"fff48fb1"
"metaPressedBackgroundColor":"ffd81b60"
"shadowColor":"55000000"
"keyPreviewBackgroundColor":"ffffffff"
"previewTextColor":"ff4a1830"
"previewSelectedColor":"55d81b60"
